### ISSUE TITLE
List of Deliverables for Milestone 1

### ISSUE THREAD

**Issue by imtvwy** [UBC-MDS/Giant_Pumpkins_Weight_Prediction#1]
List of Deliverables for Milestone 1

Written:
1. Team Contract
2. CODE_OF_CONDUCT.md
3. CONTRIBUTING.md
4. LICENSE
5. README.md (Project Proposal)
- dataset
- question
- plan
- EDA

Setup:
Public repo with structure

Coding:
- Download/save data script
- EDA (Rmd or ipynb)

**Comment by mahsasarafrazi** [comment]
The Good resource for Code of Conduct:
"http://www.idocde.net/pages/35"

**Comment by imtvwy** [comment]
Closed for Milestone 1
