### ISSUE TITLE
Suggestions for Datasets

### ISSUE THREAD

**Issue by shivajena** [UBC-MDS/Giant_Pumpkins_Weight_Prediction#2]
This issue is for suggestions for selection of datasets for our analysis to be posted in form of links and after a consensus, we can freeze one

**Comment by Rowansiv** [comment]
https://github.com/JeffSackmann/tennis_atp

https://ope.ed.gov/athletics/#/

**Comment by imtvwy** [comment]
Giant Pumpkin - explore which factors have impact on the weight of pumpkin

https://github.com/rfordatascience/tidytuesday/tree/master/data/2021/2021-10-19

**Comment by shivajena** [comment]
This is a very organised dataset resource with descriptions
https://cran.r-project.org/web/packages/fivethirtyeight/vignettes/fivethirtyeight.html

Movie ratings versus critics ratings and more..
https://fivethirtyeight.com/features/al-gores-new-movie-exposes-the-big-flaw-in-online-movie-ratings/

**Comment by mahsasarafrazi** [comment]
This one is related to marketing campaigns, whether at the end they lead to subscription or not:

https://data.world/xprizeai-ai/bank-marketing
